version: '3'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5003:5000"
    depends_on:
      - mongodb
    networks:
      - my_network

  mongodb:
    image: "mongo:latest"
    container_name: "flask-mongodb"
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - my_network

volumes:
  mongodb_data:

networks:
  my_network:
    driver: bridge
